issuer_pubkey = "8641969"
current_day = "18000"
min_age_days = "6570"
agent_key = "5555"
scope_hash = "9999"
nullifier = "8269732287621754905856504405755148899282882079009612015378864392058610586172"
