dob_days = "10000"
membership = "1"
credential_expiry_day = "22000"
holder_secret = "987654321"
issuer_sig_r = "53580247"
issuer_sig_s = "2199348286931073314642550319430003359356788987107535626163139429585799969112"

issuer_pubkey = "8641969"
current_day = "18000"
min_age_days = "6570"
agent_key = "5555"
scope_hash = "9999"
nullifier = "8269732287621754905856504405755148899282882079009612015378864392058610586172"
